namespace NodeJS
{
	interface ProcessEnv
	{
		NEXTAUTH_URL: string
		NEXTAUTH_SECRET: string
		NEXTAUTH_PROVIDER_GITHUB_ADMIN_USER_IDs: string
		NEXTAUTH_PROVIDER_GITHUB_ID: string
		NEXTAUTH_PROVIDER_GITHUB_SECRET: string
		DATABASE_TARGET_SERVICE: string
	}
}
