namespace NodeJS
{
	interface ProcessEnv
	{
		NEXTAUTH_URL: string
		NEXTAUTH_SECRET: string
		NEXTAUTH_PROVIDER_GITHUB_ADMIN_USER_IDs: string
		NEXTAUTH_PROVIDER_GITHUB_ID: string
		NEXTAUTH_PROVIDER_GITHUB_SECRET: string
		DATABASE_TARGET_SERVICE: string
		NEXT_PUBLIC_DATABASE_FILE_DATA_MAX_SIZE_KB: number
		NEXT_PUBLIC_DATABASE_FILE_THUMBNAIL_MAX_SIZE_KB: number
		NEXT_PUBLIC_IMAGE_COMPRESSION_STEP_RATE: number
		PAGINATION_PAGE_SIZE: number
	}
}
